name: Publish NuGet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Models/Models.csproj
      
      # Build the project
      - name: Build project
        run: dotnet build Models/Models.csproj -c Release --no-restore
          
      # Pack the NuGet package
      - name: Pack NuGet Package
        run: dotnet pack Models/Models.csproj -c Release --no-build -o ./nupkg
      
      # Prepare NuGet feed structure
      - name: Prepare NuGet feed structure
        run: |
          # Create proper folder structure for GitHub Pages NuGet feed
          mkdir -p ./nuget-feed/packages/dunleavymeats.models/1.0.0
          cp ./nupkg/DunleavyMeats.Models.1.0.0.nupkg ./nuget-feed/packages/dunleavymeats.models/1.0.0/
          
          # Create index.json at root for NuGet v3 feed
          cat > ./nuget-feed/index.json << 'EOL'
          {
            "version": "3.0.0",
            "resources": [
              {
                "@id": "https://dunleavy-meats.github.io/ProjectModel/packages/",
                "@type": "PackageBaseAddress/3.0.0"
              }
            ]
          }
          EOL
          
          # Create lowercase version for case-sensitive lookups
          cp ./nupkg/DunleavyMeats.Models.1.0.0.nupkg ./nuget-feed/packages/dunleavymeats.models/1.0.0/dunleavymeats.models.1.0.0.nupkg
          
          # Copy package directly to root as well (belt and suspenders approach)
          cp ./nupkg/DunleavyMeats.Models.1.0.0.nupkg ./nuget-feed/
          
      # Make the package publicly available via GitHub Pages
      - name: Deploy NuGet package to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./nuget-feed
          clean: true
      
      # Publish to GitHub Packages with public visibility
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push --skip-duplicate ./nupkg/*.nupkg \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/dunleavy-meats/index.json